
import React from 'react';
import { 
  Stethoscope, 
  Search, 
  MapPin, 
  HeartPulse, 
  Video, 
  Phone, 
  Info, 
  ShieldAlert,
  Menu,
  X,
  Languages
} from 'lucide-react';

export const COLORS = {
  primary: 'blue-600',
  secondary: 'white',
  accent: 'blue-700',
  text: 'slate-800',
  muted: 'slate-500',
};

export const UI_STRINGS = {
  EN: {
    title: 'Aapla Doctor',
    tagline: 'Your Trusted Multilingual Health Companion',
    searchPlaceholder: 'Search for medicine or symptoms...',
    medicineFinder: 'Medicine Finder',
    symptomChecker: 'Symptom Checker',
    nearbyFacilities: 'Nearby Facilities',
    wellnessTips: 'Wellness Tips',
    consultDoctor: 'Consult Doctor',
    emergencyHelpline: 'Emergency Helpline: 108',
    disclaimerTitle: 'Medical Disclaimer',
    disclaimerText: 'This is an AI-driven tool for information purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. In case of emergency, call 108 immediately.',
    accept: 'I Understand',
    medicineSearchLabel: 'Enter Medicine Name',
    medicineSearchBtn: 'Get Details',
    symptomSearchLabel: 'Describe your symptoms or emergency',
    symptomSearchBtn: 'Get Help',
    nearbyBtn: 'Find Nearest Hospitals & Pharmacies',
    warningLabel: '⚠️ IMPORTANT:',
    usageLabel: 'Common Usage:',
    dosageLabel: 'Typical Dosage:',
    firstAidLabel: 'Immediate First Aid:',
    otcLabel: 'Suggested OTC Medications:',
    contactUs: 'Contact Us',
    privacyPolicy: 'Privacy Policy',
    footerCopyright: '© 2024 Aapla Doctor. All rights reserved.',
    backToHome: 'Back to Home',
  },
  HI: {
    title: 'आपला डॉक्टर',
    tagline: 'आपका विश्वसनीय बहुभाषी स्वास्थ्य साथी',
    searchPlaceholder: 'दवा या लक्षणों की खोज करें...',
    medicineFinder: 'दवा खोजक',
    symptomChecker: 'लक्षण जाँचक',
    nearbyFacilities: 'निकटतम सुविधाएं',
    wellnessTips: 'स्वास्थ्य सुझाव',
    consultDoctor: 'डॉक्टर से परामर्श करें',
    emergencyHelpline: 'आपात्कालीन हेल्पलाइन: 108',
    disclaimerTitle: 'चिकित्सा अस्वीकरण',
    disclaimerText: 'यह केवल सूचना के उद्देश्यों के लिए एक एआई-संचालित उपकरण है। यह पेशेवर चिकित्सा सलाह, निदान या उपचार का विकल्प नहीं है। हमेशा अपनी चिकित्सा स्थिति के बारे में किसी भी प्रश्न के लिए अपने चिकित्सक या अन्य योग्य स्वास्थ्य प्रदाता की सलाह लें। आपात स्थिति में तुरंत 108 पर कॉल करें।',
    accept: 'मैं समझता हूँ',
    medicineSearchLabel: 'दवा का नाम दर्ज करें',
    medicineSearchBtn: 'विवरण प्राप्त करें',
    symptomSearchLabel: 'अपने लक्षणों या आपात स्थिति का वर्णन करें',
    symptomSearchBtn: 'मदद लें',
    nearbyBtn: 'निकटतम अस्पताल और फार्मेसी खोजें',
    warningLabel: '⚠️ महत्वपूर्ण:',
    usageLabel: 'सामान्य उपयोग:',
    dosageLabel: 'सामान्य खुराक:',
    firstAidLabel: 'तत्काल प्राथमिक चिकित्सा:',
    otcLabel: 'सुझाव दी गई ओटीसी दवाएं:',
    contactUs: 'संपर्क करें',
    privacyPolicy: 'गोपनीयता नीति',
    footerCopyright: '© 2024 आपला डॉक्टर। सर्वाधिकार सुरक्षित।',
    backToHome: 'होम पर वापस जाएं',
  },
  MR: {
    title: 'आपला डॉक्टर',
    tagline: 'तुमचा विश्वासार्ह बहुभाषिक आरोग्य सोबती',
    searchPlaceholder: 'औषध किंवा लक्षणांचा शोध घ्या...',
    medicineFinder: 'औषध शोधक',
    symptomChecker: 'लक्षण तपासक',
    nearbyFacilities: 'जवळपासच्या सुविधा',
    wellnessTips: 'आरोग्य टिपा',
    consultDoctor: 'डॉक्टरांचा सल्ला घ्या',
    emergencyHelpline: 'आणीबाणी हेल्पलाइन: 108',
    disclaimerTitle: 'वैद्यकीय डिस्क्लेमर',
    disclaimerText: 'हे केवळ माहितीच्या उद्देशासाठी एआय-सक्षम साधन आहे. हे व्यावसायिक वैद्यकीय सल्ला, निदान किंवा उपचारांसाठी पर्याय नाही. तुमच्या वैद्यकीय स्थितीबद्दल कोणत्याही प्रश्नासाठी नेहमी तुमच्या डॉक्टरांचा किंवा इतर पात्र आरोग्य सेवा पुरवठादाराचा सल्ला घ्या. आणीबाणीच्या परिस्थितीत त्वरित 108 वर कॉल करा.',
    accept: 'मला समजले',
    medicineSearchLabel: 'औषधाचे नाव टाका',
    medicineSearchBtn: 'माहिती मिळवा',
    symptomSearchLabel: 'तुमची लक्षणे किंवा आणीबाणीचे वर्णन करा',
    symptomSearchBtn: 'मदत मिळवा',
    nearbyBtn: 'जवळपासची रुग्णालये आणि फार्मसी शोधा',
    warningLabel: '⚠️ महत्त्वाचे:',
    usageLabel: 'सामान्य वापर:',
    dosageLabel: 'सामान्य डोस:',
    firstAidLabel: 'त्वरीत प्रथमोपचार:',
    otcLabel: 'सुचवलेली ओटीसी औषधे:',
    contactUs: 'आमच्याशी संपर्क साधा',
    privacyPolicy: 'गोपनीयता धोरण',
    footerCopyright: '© 2024 आपला डॉक्टर. सर्व हक्क राखीव.',
    backToHome: 'मुख्यपृष्ठावर परत जा',
  }
};
